CREATE DATABASE IF NOT EXISTS SHOPPINGCART;
USE SHOPPINGCART;

CREATE TABLE IF NOT EXISTS USERS(
IDUSER INT NOT NULL AUTO_INCREMENT,
NICKNAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
PRIMARY KEY(IDUSER,NICKNAME));

CREATE TABLE IF NOT EXISTS CATEGORY(
IDCATEGORY INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (IDCATEGORY));

CREATE TABLE IF NOT EXISTS ITEM(
IDITEM INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(80) NOT NULL,
CATEGORY INT NOT NULL,
PRICE DECIMAL(7,2) NOT NULL,
PRIMARY KEY (IDITEM)
CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(IDCATEGORY) ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SHOPPINGCARTENTRY(
IDUSER INT NOT NULL,
IDITEM INT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY(IDUSER,IDITEM),
CONSTRAINT USER_FK1 FOREIGN KEY (IDUSER) REFERENCES USERS(IDUSER) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT ITEM_FK2 FOREIGN KEY (IDITEM) REFERENCES ITEM(IDITEM) ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS ORDERS(
IDORDER INT NOT NULL AUTO_INCREMENT,
IDUSER INT NOT NULL,
PRIMARY KEY (IDORDER),
CONSTRAINT USER_FK2 FOREIGN KEY (IDUSER) REFERENCES USERS(IDUSER) ON DELETE NO ACTION ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS ORDERENTRY(
IDORDER INT NOT NULL,
IDITEM INT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY (IDORDER,IDITEM),
CONSTRAINT ORDER_FK FOREIGN KEY (IDORDER) REFERENCES ORDERS(IDORDER) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT ITEM_FK3 FOREIGN KEY (IDITEM) REFERENCES ITEM(IDITEM) ON DELETE NO ACTION ON UPDATE NO ACTION);

INSERT IGNORE INTO USERS VALUES
	(default,'Facu','12345678'),
	(default,'Iñaki','654321');
